services:
  database:
    container_name: mysql
    image: mysql
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_ALLOW_EMPTY_PASSWORD: 'no'
      MYSQL_USER: ${MYSQL_USERNAME}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - 3307:3306
    volumes:
      - db-data:/var/lib/mysql
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    networks:
      - smoelenboek
  backend:
    container_name: backend
    build:
      context: .
      dockerfile: ./docker/backend/Dockerfile
    volumes:
      - ${DOCKER_OCI_CONFIG_PATH}:/root/.oci
    depends_on:
      - database
    ports:
      - ${DOCKER_BACKEND_PORT:-8080}:8080
    networks:
      - smoelenboek
    extra_hosts:
      - "host.docker.internal:host-gateway"

networks:
  smoelenboek:

volumes:
  db-data:
