services:
  database:
    container_name: mysql
    image: mysql
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
      MYSQL_ROOT_PASSWORD: test
      MYSQL_ROOT_HOST: '%'
      MYSQL_DATABASE: smoelenboek
      MYSQL_USER: smoelenboek
      MYSQL_PASSWORD: smoelenboek
    ports:
      - 3307:3306
    volumes:
      - db-data:/var/lib/mysql
      - /etc/timezone:/etc/timezone
      - /etc/localtime:/etc/localtime
    networks:
      - smoelenboek
  backend:
    container_name: backend
    image: nouw/smoelenboek
    build:
      context: .
      dockerfile: docker/backend/Dockerfile
      target: ${TARGET:-production}
    develop:
      watch:
        - action: sync
          path: ./packages/backend/src
          target: /app/packages/backend/src
        - action: sync
          path: ./packages/backend/package.json
          target: /app/packages/backend/package.json
        - action: rebuild
          path: /app/packages/backend/yarn.lock
    volumes:
      - ${DOCKER_OCI_CONFIG_PATH:-/dev/null}:/root/.oci
    depends_on:
      - database
    ports:
      - ${DOCKER_BACKEND_PORT:-8080}:3000
    networks:
      - smoelenboek
    extra_hosts:
      - "host.docker.internal:host-gateway"

networks:
  smoelenboek:

volumes:
  db-data:
