version: '3'

services: 
  database:
    container_name: smoelenboek-mysql
    image: mysql
    restart: always
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
      MYSQL_ROOT_PASSWORD: test
      MYSQL_ROOT_HOST: '%'
      MYSQL_DATABASE: smoelenboek
      MYSQL_USER: smoelenboek
      MYSQL_PASSWORD: smoelenboek
    ports:
      - 3307:3306
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - smoelenboek
  backend:
    container_name: smoelenboek-backend
    restart: always
    image: node:20 
    working_dir: /app
    volumes:
      - .:/app
      - /app/node_modules
    command: ./bin/run_backend_dev.sh
    depends_on:
      - database
    ports:
      - 8080:8080
    networks:
        - smoelenboek 
    extra_hosts:
      - "host.docker.internal:host-gateway"
  frontend:
    container_name: smoelenboek-frontend
    restart: always
    image: node:20-alpine
    working_dir: /app
    command: ./bin/run_frontend_dev.sh
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      - backend
    ports:
      - 8000:8000
    networks:
      - smoelenboek
    extra_hosts:
      - "host.docker.internal:host-gateway"

networks:
  smoelenboek:

volumes:
  mono-node-modules: null
  db-data:
