name: Build

on:
  push:
    branches:
      - master 
      - "early-access" 
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Get version
        id: package-version
        uses: martinbeentjes/npm-get-version-action@v1.3.1

      - name: Get branch name
        id: get_branch
        run: echo "BRANCH_NAME=${GITHUB_REF#refs/heads/}" >> $GITHUB_ENV

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to registry
        uses: docker/login-action@v3
        with:
          registry: docker.io 
          username: Nouw 
          password: ${{ secrets.DOCKER_ACCESS_TOKEN }}

      - name: Build and push to container registry
        uses: docker/build-push-action@v5
        with:
          push: true
          # TODO: Should we use secrets for this instead, using /run/secrets?
          build-args: |
            DEPLOY_ENV=${{ env.BRANCH_NAME }}
          # TODO: Do something with version in docker tag
          tags: |
            nouw/smoelenboek:${{ env.BRANCH_NAME }}-latest
            nouw/smoelenboek:${{ env.BRANCH_NAME }}-${{ steps.package-version.outputs.current-version}}
