name: Build and Deploy container

on:
  push:
    branches:
      - master

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Log in to Docker Registry
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - name: Build and Push Docker Image
        run: |
          docker compose build --push 

  deploy:
    runs-on: ubuntu-latest
    needs: [build-and-push]
    steps:
     - name: Setup SSH Key
       uses: webfactory/ssh-agent@v0.5.3
       with:
         ssh-private-key: ${{ secrets.DEPLOY_GH_PRIVATE_KEY }}

     - name: Restart Docker containers
       uses: appleboy/ssh-action@v1.2.0
       with:
         host: ${{ secrets.SERVER_IP }}
         username: ${{ secrets.SERVER_USER }}
         script: |
          cd /home/${{ secrets.SERVER_USER }}/smoelenboek 
          docker pull nouw/smoelenboek
          docker compose up -d
