name: Deploy to Beta-VPS

on:
  push:
    branches:
      - early-access 

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Copy Repository to VPS
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.BETA_VPS_HOST }}
        username: ${{ secrets.BETA_VPS_USER }}
        key: ${{ secrets.BETA_VPS_KEY }}
        source: '.'
        target: '/home/fabio/smoelenboek'

    - name: Deploy using Docker Compoes
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.VPS_HOST }}
        username: ${{ secrets.VPS_USERNAME }}
        key: ${{ secrets.VPS_SSH_KEY }}
        port: ${{ secrets.VPS_SSH_PORT }}
        script: |
          cd /home/fabio/smoelenboek 
          docker-compose down
          docker-compose up -d --build
